# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agtagents',
            fields=[
                ('agentid', models.BigIntegerField(serialize=False, primary_key=True, db_column='agentID')),
                ('divisionid', models.SmallIntegerField(null=True, db_column='divisionID', blank=True)),
                ('corporationid', models.BigIntegerField(null=True, db_column='corporationID', blank=True)),
                ('locationid', models.BigIntegerField(null=True, db_column='locationID', blank=True)),
                ('level', models.SmallIntegerField(null=True, blank=True)),
                ('quality', models.SmallIntegerField(null=True, blank=True)),
                ('agenttypeid', models.BigIntegerField(null=True, db_column='agentTypeID', blank=True)),
                ('islocator', models.NullBooleanField(db_column='isLocator')),
            ],
            options={
                'db_table': 'agtAgents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agtagenttypes',
            fields=[
                ('agenttypeid', models.BigIntegerField(serialize=False, primary_key=True, db_column='agentTypeID')),
                ('agenttype', models.TextField(db_column='agentType', blank=True)),
            ],
            options={
                'db_table': 'agtAgentTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agtresearchagents',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('agentid', models.BigIntegerField(db_column='agentID')),
                ('typeid', models.BigIntegerField(db_column='typeID')),
            ],
            options={
                'db_table': 'agtResearchAgents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certcerts',
            fields=[
                ('certid', models.BigIntegerField(serialize=False, primary_key=True, db_column='certID')),
                ('description', models.TextField(blank=True)),
                ('groupid', models.BigIntegerField(null=True, blank=True)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'certCerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certmasteries',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('masterylevel', models.BigIntegerField(null=True, db_column='masteryLevel', blank=True)),
                ('certid', models.BigIntegerField(null=True, db_column='certID', blank=True)),
            ],
            options={
                'db_table': 'certMasteries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certskills',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('certid', models.BigIntegerField(null=True, db_column='certID', blank=True)),
                ('skillid', models.BigIntegerField(null=True, db_column='skillID', blank=True)),
                ('certlevelint', models.BigIntegerField(null=True, db_column='certLevelInt', blank=True)),
                ('skilllevel', models.BigIntegerField(null=True, db_column='skillLevel', blank=True)),
                ('certleveltext', models.TextField(db_column='certLevelText', blank=True)),
            ],
            options={
                'db_table': 'certSkills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrancestries',
            fields=[
                ('ancestryid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='ancestryID')),
                ('ancestryname', models.TextField(db_column='ancestryName', blank=True)),
                ('bloodlineid', models.SmallIntegerField(null=True, db_column='bloodlineID', blank=True)),
                ('description', models.TextField(blank=True)),
                ('perception', models.SmallIntegerField(null=True, blank=True)),
                ('willpower', models.SmallIntegerField(null=True, blank=True)),
                ('charisma', models.SmallIntegerField(null=True, blank=True)),
                ('memory', models.SmallIntegerField(null=True, blank=True)),
                ('intelligence', models.SmallIntegerField(null=True, blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('shortdescription', models.TextField(db_column='shortDescription', blank=True)),
            ],
            options={
                'db_table': 'chrAncestries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrattributes',
            fields=[
                ('attributeid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='attributeID')),
                ('attributename', models.TextField(db_column='attributeName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('shortdescription', models.TextField(db_column='shortDescription', blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'chrAttributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrbloodlines',
            fields=[
                ('bloodlineid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='bloodlineID')),
                ('bloodlinename', models.TextField(db_column='bloodlineName', blank=True)),
                ('raceid', models.SmallIntegerField(null=True, db_column='raceID', blank=True)),
                ('description', models.TextField(blank=True)),
                ('maledescription', models.TextField(db_column='maleDescription', blank=True)),
                ('femaledescription', models.TextField(db_column='femaleDescription', blank=True)),
                ('shiptypeid', models.BigIntegerField(null=True, db_column='shipTypeID', blank=True)),
                ('corporationid', models.BigIntegerField(null=True, db_column='corporationID', blank=True)),
                ('perception', models.SmallIntegerField(null=True, blank=True)),
                ('willpower', models.SmallIntegerField(null=True, blank=True)),
                ('charisma', models.SmallIntegerField(null=True, blank=True)),
                ('memory', models.SmallIntegerField(null=True, blank=True)),
                ('intelligence', models.SmallIntegerField(null=True, blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('shortdescription', models.TextField(db_column='shortDescription', blank=True)),
                ('shortmaledescription', models.TextField(db_column='shortMaleDescription', blank=True)),
                ('shortfemaledescription', models.TextField(db_column='shortFemaleDescription', blank=True)),
            ],
            options={
                'db_table': 'chrBloodlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrfactions',
            fields=[
                ('factionid', models.BigIntegerField(serialize=False, primary_key=True, db_column='factionID')),
                ('factionname', models.TextField(db_column='factionName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('raceids', models.BigIntegerField(null=True, db_column='raceIDs', blank=True)),
                ('solarsystemid', models.BigIntegerField(null=True, db_column='solarSystemID', blank=True)),
                ('corporationid', models.BigIntegerField(null=True, db_column='corporationID', blank=True)),
                ('sizefactor', models.FloatField(null=True, db_column='sizeFactor', blank=True)),
                ('stationcount', models.SmallIntegerField(null=True, db_column='stationCount', blank=True)),
                ('stationsystemcount', models.SmallIntegerField(null=True, db_column='stationSystemCount', blank=True)),
                ('militiacorporationid', models.BigIntegerField(null=True, db_column='militiaCorporationID', blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
            ],
            options={
                'db_table': 'chrFactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrraces',
            fields=[
                ('raceid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='raceID')),
                ('racename', models.TextField(db_column='raceName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('shortdescription', models.TextField(db_column='shortDescription', blank=True)),
            ],
            options={
                'db_table': 'chrRaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpactivities',
            fields=[
                ('activityid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='activityID')),
                ('activityname', models.TextField(db_column='activityName', blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crpActivities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporationdivisions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('corporationid', models.BigIntegerField(db_column='corporationID')),
                ('divisionid', models.SmallIntegerField(db_column='divisionID')),
                ('size', models.SmallIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'crpNPCCorporationDivisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporationresearchfields',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('skillid', models.BigIntegerField(db_column='skillID')),
                ('corporationid', models.BigIntegerField(db_column='corporationID')),
            ],
            options={
                'db_table': 'crpNPCCorporationResearchFields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporations',
            fields=[
                ('corporationid', models.BigIntegerField(serialize=False, primary_key=True, db_column='corporationID')),
                ('size', models.CharField(max_length=1, blank=True)),
                ('extent', models.CharField(max_length=1, blank=True)),
                ('solarsystemid', models.BigIntegerField(null=True, db_column='solarSystemID', blank=True)),
                ('investorid1', models.BigIntegerField(null=True, db_column='investorID1', blank=True)),
                ('investorshares1', models.SmallIntegerField(null=True, db_column='investorShares1', blank=True)),
                ('investorid2', models.BigIntegerField(null=True, db_column='investorID2', blank=True)),
                ('investorshares2', models.SmallIntegerField(null=True, db_column='investorShares2', blank=True)),
                ('investorid3', models.BigIntegerField(null=True, db_column='investorID3', blank=True)),
                ('investorshares3', models.SmallIntegerField(null=True, db_column='investorShares3', blank=True)),
                ('investorid4', models.BigIntegerField(null=True, db_column='investorID4', blank=True)),
                ('investorshares4', models.SmallIntegerField(null=True, db_column='investorShares4', blank=True)),
                ('friendid', models.BigIntegerField(null=True, db_column='friendID', blank=True)),
                ('enemyid', models.BigIntegerField(null=True, db_column='enemyID', blank=True)),
                ('publicshares', models.BigIntegerField(null=True, db_column='publicShares', blank=True)),
                ('initialprice', models.BigIntegerField(null=True, db_column='initialPrice', blank=True)),
                ('minsecurity', models.FloatField(null=True, db_column='minSecurity', blank=True)),
                ('scattered', models.NullBooleanField()),
                ('fringe', models.SmallIntegerField(null=True, blank=True)),
                ('corridor', models.SmallIntegerField(null=True, blank=True)),
                ('hub', models.SmallIntegerField(null=True, blank=True)),
                ('border', models.SmallIntegerField(null=True, blank=True)),
                ('factionid', models.BigIntegerField(null=True, db_column='factionID', blank=True)),
                ('sizefactor', models.FloatField(null=True, db_column='sizeFactor', blank=True)),
                ('stationcount', models.SmallIntegerField(null=True, db_column='stationCount', blank=True)),
                ('stationsystemcount', models.SmallIntegerField(null=True, db_column='stationSystemCount', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
            ],
            options={
                'db_table': 'crpNPCCorporations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpccorporationtrades',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('corporationid', models.BigIntegerField(db_column='corporationID')),
                ('typeid', models.BigIntegerField(db_column='typeID')),
            ],
            options={
                'db_table': 'crpNPCCorporationTrades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crpnpcdivisions',
            fields=[
                ('divisionid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='divisionID')),
                ('divisionname', models.TextField(db_column='divisionName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('leadertype', models.TextField(db_column='leaderType', blank=True)),
            ],
            options={
                'db_table': 'crpNPCDivisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmattributecategories',
            fields=[
                ('categoryid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='categoryID')),
                ('categoryname', models.TextField(db_column='categoryName', blank=True)),
                ('categorydescription', models.TextField(db_column='categoryDescription', blank=True)),
            ],
            options={
                'db_table': 'dgmAttributeCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmattributetypes',
            fields=[
                ('attributeid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='attributeID')),
                ('attributename', models.TextField(db_column='attributeName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('defaultvalue', models.FloatField(null=True, db_column='defaultValue', blank=True)),
                ('published', models.NullBooleanField()),
                ('displayname', models.TextField(db_column='displayName', blank=True)),
                ('unitid', models.SmallIntegerField(null=True, db_column='unitID', blank=True)),
                ('stackable', models.NullBooleanField()),
                ('highisgood', models.NullBooleanField(db_column='highIsGood')),
                ('categoryid', models.SmallIntegerField(null=True, db_column='categoryID', blank=True)),
            ],
            options={
                'db_table': 'dgmAttributeTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmeffects',
            fields=[
                ('effectid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='effectID')),
                ('effectname', models.TextField(db_column='effectName', blank=True)),
                ('effectcategory', models.SmallIntegerField(null=True, db_column='effectCategory', blank=True)),
                ('preexpression', models.BigIntegerField(null=True, db_column='preExpression', blank=True)),
                ('postexpression', models.BigIntegerField(null=True, db_column='postExpression', blank=True)),
                ('description', models.TextField(blank=True)),
                ('guid', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('isoffensive', models.NullBooleanField(db_column='isOffensive')),
                ('isassistance', models.NullBooleanField(db_column='isAssistance')),
                ('durationattributeid', models.SmallIntegerField(null=True, db_column='durationAttributeID', blank=True)),
                ('trackingspeedattributeid', models.SmallIntegerField(null=True, db_column='trackingSpeedAttributeID', blank=True)),
                ('dischargeattributeid', models.SmallIntegerField(null=True, db_column='dischargeAttributeID', blank=True)),
                ('rangeattributeid', models.SmallIntegerField(null=True, db_column='rangeAttributeID', blank=True)),
                ('falloffattributeid', models.SmallIntegerField(null=True, db_column='falloffAttributeID', blank=True)),
                ('disallowautorepeat', models.NullBooleanField(db_column='disallowAutoRepeat')),
                ('published', models.NullBooleanField()),
                ('displayname', models.TextField(db_column='displayName', blank=True)),
                ('iswarpsafe', models.NullBooleanField(db_column='isWarpSafe')),
                ('rangechance', models.NullBooleanField(db_column='rangeChance')),
                ('electronicchance', models.NullBooleanField(db_column='electronicChance')),
                ('propulsionchance', models.NullBooleanField(db_column='propulsionChance')),
                ('distribution', models.SmallIntegerField(null=True, blank=True)),
                ('sfxname', models.TextField(db_column='sfxName', blank=True)),
                ('npcusagechanceattributeid', models.SmallIntegerField(null=True, db_column='npcUsageChanceAttributeID', blank=True)),
                ('npcactivationchanceattributeid', models.SmallIntegerField(null=True, db_column='npcActivationChanceAttributeID', blank=True)),
                ('fittingusagechanceattributeid', models.SmallIntegerField(null=True, db_column='fittingUsageChanceAttributeID', blank=True)),
                ('modifierinfo', models.TextField(db_column='modifierInfo', blank=True)),
            ],
            options={
                'db_table': 'dgmEffects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmexpressions',
            fields=[
                ('expressionid', models.BigIntegerField(serialize=False, primary_key=True, db_column='expressionID')),
                ('operandid', models.BigIntegerField(null=True, db_column='operandID', blank=True)),
                ('arg1', models.BigIntegerField(null=True, blank=True)),
                ('arg2', models.BigIntegerField(null=True, blank=True)),
                ('expressionvalue', models.TextField(db_column='expressionValue', blank=True)),
                ('description', models.TextField(blank=True)),
                ('expressionname', models.TextField(db_column='expressionName', blank=True)),
                ('expressiontypeid', models.BigIntegerField(null=True, db_column='expressionTypeID', blank=True)),
                ('expressiongroupid', models.SmallIntegerField(null=True, db_column='expressionGroupID', blank=True)),
                ('expressionattributeid', models.SmallIntegerField(null=True, db_column='expressionAttributeID', blank=True)),
            ],
            options={
                'db_table': 'dgmExpressions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmtypeattributes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('attributeid', models.SmallIntegerField(db_column='attributeID')),
                ('valueint', models.BigIntegerField(null=True, db_column='valueInt', blank=True)),
                ('valuefloat', models.FloatField(null=True, db_column='valueFloat', blank=True)),
            ],
            options={
                'db_table': 'dgmTypeAttributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dgmtypeeffects',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('effectid', models.SmallIntegerField(db_column='effectID')),
                ('isdefault', models.NullBooleanField(db_column='isDefault')),
            ],
            options={
                'db_table': 'dgmTypeEffects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eveicons',
            fields=[
                ('iconid', models.BigIntegerField(serialize=False, primary_key=True, db_column='iconID')),
                ('iconfile', models.TextField(db_column='iconFile')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'eveIcons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eveunits',
            fields=[
                ('unitid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='unitID')),
                ('unitname', models.TextField(db_column='unitName', blank=True)),
                ('displayname', models.TextField(db_column='displayName', blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'eveUnits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('time', models.BigIntegerField(null=True, blank=True)),
                ('activityid', models.BigIntegerField(db_column='activityID')),
            ],
            options={
                'db_table': 'industryActivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivitymaterials',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('activityid', models.BigIntegerField(null=True, db_column='activityID', blank=True)),
                ('materialtypeid', models.BigIntegerField(null=True, db_column='materialTypeID', blank=True)),
                ('quantity', models.BigIntegerField(null=True, blank=True)),
                ('consume', models.SmallIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'industryActivityMaterials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityprobabilities',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('activityid', models.BigIntegerField(null=True, db_column='activityID', blank=True)),
                ('producttypeid', models.BigIntegerField(null=True, db_column='productTypeID', blank=True)),
                ('probability', models.DecimalField(null=True, max_digits=3, decimal_places=2, blank=True)),
            ],
            options={
                'db_table': 'industryActivityProbabilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityproducts',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('activityid', models.BigIntegerField(null=True, db_column='activityID', blank=True)),
                ('producttypeid', models.BigIntegerField(null=True, db_column='productTypeID', blank=True)),
                ('quantity', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'industryActivityProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryactivityskills',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('activityid', models.BigIntegerField(null=True, db_column='activityID', blank=True)),
                ('skillid', models.BigIntegerField(null=True, db_column='skillID', blank=True)),
                ('level', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'industryActivitySkills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industryblueprints',
            fields=[
                ('typeid', models.BigIntegerField(serialize=False, primary_key=True, db_column='typeID')),
                ('maxproductionlimit', models.BigIntegerField(null=True, db_column='maxProductionLimit', blank=True)),
            ],
            options={
                'db_table': 'industryBlueprints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcategories',
            fields=[
                ('categoryid', models.BigIntegerField(serialize=False, primary_key=True, db_column='categoryID')),
                ('categoryname', models.TextField(db_column='categoryName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('published', models.NullBooleanField()),
            ],
            options={
                'db_table': 'invCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcontrabandtypes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('factionid', models.BigIntegerField(db_column='factionID')),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('standingloss', models.FloatField(null=True, db_column='standingLoss', blank=True)),
                ('confiscateminsec', models.FloatField(null=True, db_column='confiscateMinSec', blank=True)),
                ('finebyvalue', models.FloatField(null=True, db_column='fineByValue', blank=True)),
                ('attackminsec', models.FloatField(null=True, db_column='attackMinSec', blank=True)),
            ],
            options={
                'db_table': 'invContrabandTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcontroltowerresourcepurposes',
            fields=[
                ('purpose', models.SmallIntegerField(serialize=False, primary_key=True)),
                ('purposetext', models.TextField(db_column='purposeText', blank=True)),
            ],
            options={
                'db_table': 'invControlTowerResourcePurposes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invcontroltowerresources',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('controltowertypeid', models.BigIntegerField(db_column='controlTowerTypeID')),
                ('resourcetypeid', models.BigIntegerField(db_column='resourceTypeID')),
                ('purpose', models.SmallIntegerField(null=True, blank=True)),
                ('quantity', models.BigIntegerField(null=True, blank=True)),
                ('minsecuritylevel', models.FloatField(null=True, db_column='minSecurityLevel', blank=True)),
                ('factionid', models.BigIntegerField(null=True, db_column='factionID', blank=True)),
            ],
            options={
                'db_table': 'invControlTowerResources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invflags',
            fields=[
                ('flagid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='flagID')),
                ('flagname', models.TextField(db_column='flagName', blank=True)),
                ('flagtext', models.TextField(db_column='flagText', blank=True)),
                ('orderid', models.BigIntegerField(null=True, db_column='orderID', blank=True)),
            ],
            options={
                'db_table': 'invFlags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invgroups',
            fields=[
                ('groupid', models.BigIntegerField(serialize=False, primary_key=True, db_column='groupID')),
                ('categoryid', models.BigIntegerField(null=True, db_column='categoryID', blank=True)),
                ('groupname', models.TextField(db_column='groupName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('usebaseprice', models.NullBooleanField(db_column='useBasePrice')),
                ('allowmanufacture', models.NullBooleanField(db_column='allowManufacture')),
                ('allowrecycler', models.NullBooleanField(db_column='allowRecycler')),
                ('anchored', models.NullBooleanField()),
                ('anchorable', models.NullBooleanField()),
                ('fittablenonsingleton', models.NullBooleanField(db_column='fittableNonSingleton')),
                ('published', models.NullBooleanField()),
            ],
            options={
                'db_table': 'invGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invitems',
            fields=[
                ('itemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='itemID')),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('ownerid', models.BigIntegerField(db_column='ownerID')),
                ('locationid', models.BigIntegerField(db_column='locationID')),
                ('flagid', models.SmallIntegerField(db_column='flagID')),
                ('quantity', models.BigIntegerField()),
            ],
            options={
                'db_table': 'invItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invmarketgroups',
            fields=[
                ('marketgroupid', models.BigIntegerField(serialize=False, primary_key=True, db_column='marketGroupID')),
                ('parentgroupid', models.BigIntegerField(null=True, db_column='parentGroupID', blank=True)),
                ('marketgroupname', models.TextField(db_column='marketGroupName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
                ('hastypes', models.NullBooleanField(db_column='hasTypes')),
            ],
            options={
                'db_table': 'invMarketGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invmetagroups',
            fields=[
                ('metagroupid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='metaGroupID')),
                ('metagroupname', models.TextField(db_column='metaGroupName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
            ],
            options={
                'db_table': 'invMetaGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invmetatypes',
            fields=[
                ('typeid', models.BigIntegerField(serialize=False, primary_key=True, db_column='typeID')),
                ('parenttypeid', models.BigIntegerField(null=True, db_column='parentTypeID', blank=True)),
                ('metagroupid', models.SmallIntegerField(null=True, db_column='metaGroupID', blank=True)),
            ],
            options={
                'db_table': 'invMetaTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invnames',
            fields=[
                ('itemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='itemID')),
                ('itemname', models.TextField(db_column='itemName')),
            ],
            options={
                'db_table': 'invNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invpositions',
            fields=[
                ('itemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='itemID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('yaw', models.FloatField(null=True, blank=True)),
                ('pitch', models.FloatField(null=True, blank=True)),
                ('roll', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'invPositions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtraits',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('skillid', models.BigIntegerField(null=True, db_column='skillID', blank=True)),
                ('bonus', models.FloatField(null=True, blank=True)),
                ('bonustext', models.TextField(db_column='bonusText', blank=True)),
                ('unitid', models.BigIntegerField(null=True, db_column='unitID', blank=True)),
            ],
            options={
                'db_table': 'invTraits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypematerials',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('materialtypeid', models.BigIntegerField(db_column='materialTypeID')),
                ('quantity', models.BigIntegerField()),
            ],
            options={
                'db_table': 'invTypeMaterials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypereactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reactiontypeid', models.BigIntegerField(db_column='reactionTypeID')),
                ('input', models.BooleanField(default=False)),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('quantity', models.SmallIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'invTypeReactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypes',
            fields=[
                ('typeid', models.BigIntegerField(serialize=False, primary_key=True, db_column='typeID')),
                ('groupid', models.BigIntegerField(null=True, db_column='groupID', blank=True)),
                ('typename', models.TextField(db_column='typeName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('mass', models.FloatField(null=True, blank=True)),
                ('volume', models.FloatField(null=True, blank=True)),
                ('capacity', models.FloatField(null=True, blank=True)),
                ('portionsize', models.BigIntegerField(null=True, db_column='portionSize', blank=True)),
                ('raceid', models.SmallIntegerField(null=True, db_column='raceID', blank=True)),
                ('baseprice', models.DecimalField(null=True, decimal_places=4, max_digits=19, db_column='basePrice', blank=True)),
                ('published', models.NullBooleanField()),
                ('marketgroupid', models.BigIntegerField(null=True, db_column='marketGroupID', blank=True)),
                ('chanceofduplicating', models.FloatField(null=True, db_column='chanceOfDuplicating', blank=True)),
            ],
            options={
                'db_table': 'invTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invuniquenames',
            fields=[
                ('itemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='itemID')),
                ('itemname', models.TextField(unique=True, db_column='itemName')),
                ('groupid', models.BigIntegerField(null=True, db_column='groupID', blank=True)),
            ],
            options={
                'db_table': 'invUniqueNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invvolumes',
            fields=[
                ('groupid', models.BigIntegerField(serialize=False, primary_key=True)),
                ('volume', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'invVolumes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapcelestialstatistics',
            fields=[
                ('celestialid', models.BigIntegerField(serialize=False, primary_key=True, db_column='celestialID')),
                ('temperature', models.FloatField(null=True, blank=True)),
                ('spectralclass', models.TextField(db_column='spectralClass', blank=True)),
                ('luminosity', models.FloatField(null=True, blank=True)),
                ('age', models.FloatField(null=True, blank=True)),
                ('life', models.FloatField(null=True, blank=True)),
                ('orbitradius', models.FloatField(null=True, db_column='orbitRadius', blank=True)),
                ('eccentricity', models.FloatField(null=True, blank=True)),
                ('massdust', models.FloatField(null=True, db_column='massDust', blank=True)),
                ('massgas', models.FloatField(null=True, db_column='massGas', blank=True)),
                ('fragmented', models.BigIntegerField(null=True, blank=True)),
                ('density', models.FloatField(null=True, blank=True)),
                ('surfacegravity', models.FloatField(null=True, db_column='surfaceGravity', blank=True)),
                ('escapevelocity', models.FloatField(null=True, db_column='escapeVelocity', blank=True)),
                ('orbitperiod', models.FloatField(null=True, db_column='orbitPeriod', blank=True)),
                ('rotationrate', models.FloatField(null=True, db_column='rotationRate', blank=True)),
                ('locked', models.BigIntegerField(null=True, blank=True)),
                ('pressure', models.BigIntegerField(null=True, blank=True)),
                ('radius', models.BigIntegerField(null=True, blank=True)),
                ('mass', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mapCelestialStatistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapconstellationjumps',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fromregionid', models.BigIntegerField(null=True, db_column='fromRegionID', blank=True)),
                ('fromconstellationid', models.BigIntegerField(db_column='fromConstellationID')),
                ('toconstellationid', models.BigIntegerField(db_column='toConstellationID')),
                ('toregionid', models.BigIntegerField(null=True, db_column='toRegionID', blank=True)),
            ],
            options={
                'db_table': 'mapConstellationJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapconstellations',
            fields=[
                ('regionid', models.BigIntegerField(null=True, db_column='regionID', blank=True)),
                ('constellationid', models.BigIntegerField(serialize=False, primary_key=True, db_column='constellationID')),
                ('constellationname', models.TextField(db_column='constellationName', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('xmin', models.FloatField(null=True, db_column='xMin', blank=True)),
                ('xmax', models.FloatField(null=True, db_column='xMax', blank=True)),
                ('ymin', models.FloatField(null=True, db_column='yMin', blank=True)),
                ('ymax', models.FloatField(null=True, db_column='yMax', blank=True)),
                ('zmin', models.FloatField(null=True, db_column='zMin', blank=True)),
                ('zmax', models.FloatField(null=True, db_column='zMax', blank=True)),
                ('factionid', models.BigIntegerField(null=True, db_column='factionID', blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mapConstellations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapdenormalize',
            fields=[
                ('itemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='itemID')),
                ('typeid', models.BigIntegerField(null=True, db_column='typeID', blank=True)),
                ('groupid', models.BigIntegerField(null=True, db_column='groupID', blank=True)),
                ('solarsystemid', models.BigIntegerField(null=True, db_column='solarSystemID', blank=True)),
                ('constellationid', models.BigIntegerField(null=True, db_column='constellationID', blank=True)),
                ('regionid', models.BigIntegerField(null=True, db_column='regionID', blank=True)),
                ('orbitid', models.BigIntegerField(null=True, db_column='orbitID', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
                ('itemname', models.TextField(db_column='itemName', blank=True)),
                ('security', models.FloatField(null=True, blank=True)),
                ('celestialindex', models.BigIntegerField(null=True, db_column='celestialIndex', blank=True)),
                ('orbitindex', models.BigIntegerField(null=True, db_column='orbitIndex', blank=True)),
            ],
            options={
                'db_table': 'mapDenormalize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapjumps',
            fields=[
                ('stargateid', models.BigIntegerField(serialize=False, primary_key=True, db_column='stargateID')),
                ('destinationid', models.BigIntegerField(null=True, db_column='destinationID', blank=True)),
            ],
            options={
                'db_table': 'mapJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maplandmarks',
            fields=[
                ('landmarkid', models.BigIntegerField(serialize=False, primary_key=True, db_column='landmarkID')),
                ('landmarkname', models.TextField(db_column='landmarkName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('locationid', models.BigIntegerField(null=True, db_column='locationID', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('iconid', models.BigIntegerField(null=True, db_column='iconID', blank=True)),
            ],
            options={
                'db_table': 'mapLandmarks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maplocationscenes',
            fields=[
                ('locationid', models.BigIntegerField(serialize=False, primary_key=True, db_column='locationID')),
                ('graphicid', models.BigIntegerField(null=True, db_column='graphicID', blank=True)),
            ],
            options={
                'db_table': 'mapLocationScenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maplocationwormholeclasses',
            fields=[
                ('locationid', models.BigIntegerField(serialize=False, primary_key=True, db_column='locationID')),
                ('wormholeclassid', models.BigIntegerField(null=True, db_column='wormholeClassID', blank=True)),
            ],
            options={
                'db_table': 'mapLocationWormholeClasses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapregionjumps',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fromregionid', models.BigIntegerField(db_column='fromRegionID')),
                ('toregionid', models.BigIntegerField(db_column='toRegionID')),
            ],
            options={
                'db_table': 'mapRegionJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapregions',
            fields=[
                ('regionid', models.BigIntegerField(serialize=False, primary_key=True, db_column='regionID')),
                ('regionname', models.TextField(db_column='regionName', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('xmin', models.FloatField(null=True, db_column='xMin', blank=True)),
                ('xmax', models.FloatField(null=True, db_column='xMax', blank=True)),
                ('ymin', models.FloatField(null=True, db_column='yMin', blank=True)),
                ('ymax', models.FloatField(null=True, db_column='yMax', blank=True)),
                ('zmin', models.FloatField(null=True, db_column='zMin', blank=True)),
                ('zmax', models.FloatField(null=True, db_column='zMax', blank=True)),
                ('factionid', models.BigIntegerField(null=True, db_column='factionID', blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mapRegions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapsolarsystemjumps',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fromregionid', models.BigIntegerField(null=True, db_column='fromRegionID', blank=True)),
                ('fromconstellationid', models.BigIntegerField(null=True, db_column='fromConstellationID', blank=True)),
                ('fromsolarsystemid', models.BigIntegerField(db_column='fromSolarSystemID')),
                ('tosolarsystemid', models.BigIntegerField(db_column='toSolarSystemID')),
                ('toconstellationid', models.BigIntegerField(null=True, db_column='toConstellationID', blank=True)),
                ('toregionid', models.BigIntegerField(null=True, db_column='toRegionID', blank=True)),
            ],
            options={
                'db_table': 'mapSolarSystemJumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapsolarsystems',
            fields=[
                ('regionid', models.BigIntegerField(null=True, db_column='regionID', blank=True)),
                ('constellationid', models.BigIntegerField(null=True, db_column='constellationID', blank=True)),
                ('solarsystemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='solarSystemID')),
                ('solarsystemname', models.TextField(db_column='solarSystemName', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('xmin', models.FloatField(null=True, db_column='xMin', blank=True)),
                ('xmax', models.FloatField(null=True, db_column='xMax', blank=True)),
                ('ymin', models.FloatField(null=True, db_column='yMin', blank=True)),
                ('ymax', models.FloatField(null=True, db_column='yMax', blank=True)),
                ('zmin', models.FloatField(null=True, db_column='zMin', blank=True)),
                ('zmax', models.FloatField(null=True, db_column='zMax', blank=True)),
                ('luminosity', models.FloatField(null=True, blank=True)),
                ('border', models.SmallIntegerField(null=True, blank=True)),
                ('fringe', models.SmallIntegerField(null=True, blank=True)),
                ('corridor', models.SmallIntegerField(null=True, blank=True)),
                ('hub', models.SmallIntegerField(null=True, blank=True)),
                ('international', models.SmallIntegerField(null=True, blank=True)),
                ('regional', models.SmallIntegerField(null=True, blank=True)),
                ('constellation', models.SmallIntegerField(null=True, blank=True)),
                ('security', models.FloatField(null=True, blank=True)),
                ('factionid', models.BigIntegerField(null=True, db_column='factionID', blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
                ('suntypeid', models.BigIntegerField(null=True, db_column='sunTypeID', blank=True)),
                ('securityclass', models.TextField(db_column='securityClass', blank=True)),
            ],
            options={
                'db_table': 'mapSolarSystems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapuniverse',
            fields=[
                ('universeid', models.BigIntegerField(serialize=False, primary_key=True, db_column='universeID')),
                ('universename', models.TextField(db_column='universeName', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('xmin', models.FloatField(null=True, db_column='xMin', blank=True)),
                ('xmax', models.FloatField(null=True, db_column='xMax', blank=True)),
                ('ymin', models.FloatField(null=True, db_column='yMin', blank=True)),
                ('ymax', models.FloatField(null=True, db_column='yMax', blank=True)),
                ('zmin', models.FloatField(null=True, db_column='zMin', blank=True)),
                ('zmax', models.FloatField(null=True, db_column='zMax', blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mapUniverse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetschematics',
            fields=[
                ('schematicid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='schematicID')),
                ('schematicname', models.TextField(db_column='schematicName', blank=True)),
                ('cycletime', models.BigIntegerField(null=True, db_column='cycleTime', blank=True)),
            ],
            options={
                'db_table': 'planetSchematics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetschematicspinmap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('schematicid', models.SmallIntegerField(db_column='schematicID')),
                ('pintypeid', models.BigIntegerField(db_column='pinTypeID')),
            ],
            options={
                'db_table': 'planetSchematicsPinMap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetschematicstypemap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('schematicid', models.SmallIntegerField(db_column='schematicID')),
                ('typeid', models.BigIntegerField(db_column='typeID')),
                ('quantity', models.SmallIntegerField(null=True, blank=True)),
                ('isinput', models.NullBooleanField(db_column='isInput')),
            ],
            options={
                'db_table': 'planetSchematicsTypeMap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramactivities',
            fields=[
                ('activityid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='activityID')),
                ('activityname', models.TextField(db_column='activityName', blank=True)),
                ('iconno', models.TextField(db_column='iconNo', blank=True)),
                ('description', models.TextField(blank=True)),
                ('published', models.NullBooleanField()),
            ],
            options={
                'db_table': 'ramActivities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinestations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stationid', models.BigIntegerField(db_column='stationID')),
                ('assemblylinetypeid', models.SmallIntegerField(db_column='assemblyLineTypeID')),
                ('quantity', models.SmallIntegerField(null=True, blank=True)),
                ('stationtypeid', models.BigIntegerField(null=True, db_column='stationTypeID', blank=True)),
                ('ownerid', models.BigIntegerField(null=True, db_column='ownerID', blank=True)),
                ('solarsystemid', models.BigIntegerField(null=True, db_column='solarSystemID', blank=True)),
                ('regionid', models.BigIntegerField(null=True, db_column='regionID', blank=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinetypedetailpercategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('assemblylinetypeid', models.SmallIntegerField(db_column='assemblyLineTypeID')),
                ('categoryid', models.BigIntegerField(db_column='categoryID')),
                ('timemultiplier', models.FloatField(null=True, db_column='timeMultiplier', blank=True)),
                ('materialmultiplier', models.FloatField(null=True, db_column='materialMultiplier', blank=True)),
                ('costmultiplier', models.FloatField(null=True, db_column='costMultiplier', blank=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineTypeDetailPerCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinetypedetailpergroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('assemblylinetypeid', models.SmallIntegerField(db_column='assemblyLineTypeID')),
                ('groupid', models.BigIntegerField(db_column='groupID')),
                ('timemultiplier', models.FloatField(null=True, db_column='timeMultiplier', blank=True)),
                ('materialmultiplier', models.FloatField(null=True, db_column='materialMultiplier', blank=True)),
                ('costmultiplier', models.FloatField(null=True, db_column='costMultiplier', blank=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineTypeDetailPerGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramassemblylinetypes',
            fields=[
                ('assemblylinetypeid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='assemblyLineTypeID')),
                ('assemblylinetypename', models.TextField(db_column='assemblyLineTypeName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('basetimemultiplier', models.FloatField(null=True, db_column='baseTimeMultiplier', blank=True)),
                ('basematerialmultiplier', models.FloatField(null=True, db_column='baseMaterialMultiplier', blank=True)),
                ('basecostmultiplier', models.FloatField(null=True, db_column='baseCostMultiplier', blank=True)),
                ('volume', models.FloatField(null=True, blank=True)),
                ('activityid', models.SmallIntegerField(null=True, db_column='activityID', blank=True)),
                ('mincostperhour', models.FloatField(null=True, db_column='minCostPerHour', blank=True)),
            ],
            options={
                'db_table': 'ramAssemblyLineTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raminstallationtypecontents',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('installationtypeid', models.BigIntegerField(db_column='installationTypeID')),
                ('assemblylinetypeid', models.SmallIntegerField(db_column='assemblyLineTypeID')),
                ('quantity', models.SmallIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'ramInstallationTypeContents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staoperations',
            fields=[
                ('activityid', models.SmallIntegerField(null=True, db_column='activityID', blank=True)),
                ('operationid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='operationID')),
                ('operationname', models.TextField(db_column='operationName', blank=True)),
                ('description', models.TextField(blank=True)),
                ('fringe', models.SmallIntegerField(null=True, blank=True)),
                ('corridor', models.SmallIntegerField(null=True, blank=True)),
                ('hub', models.SmallIntegerField(null=True, blank=True)),
                ('border', models.SmallIntegerField(null=True, blank=True)),
                ('ratio', models.SmallIntegerField(null=True, blank=True)),
                ('caldaristationtypeid', models.BigIntegerField(null=True, db_column='caldariStationTypeID', blank=True)),
                ('minmatarstationtypeid', models.BigIntegerField(null=True, db_column='minmatarStationTypeID', blank=True)),
                ('amarrstationtypeid', models.BigIntegerField(null=True, db_column='amarrStationTypeID', blank=True)),
                ('gallentestationtypeid', models.BigIntegerField(null=True, db_column='gallenteStationTypeID', blank=True)),
                ('jovestationtypeid', models.BigIntegerField(null=True, db_column='joveStationTypeID', blank=True)),
            ],
            options={
                'db_table': 'staOperations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staoperationservices',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('operationid', models.SmallIntegerField(db_column='operationID')),
                ('serviceid', models.BigIntegerField(db_column='serviceID')),
            ],
            options={
                'db_table': 'staOperationServices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staservices',
            fields=[
                ('serviceid', models.BigIntegerField(serialize=False, primary_key=True, db_column='serviceID')),
                ('servicename', models.TextField(db_column='serviceName', blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'staServices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stastations',
            fields=[
                ('stationid', models.BigIntegerField(serialize=False, primary_key=True, db_column='stationID')),
                ('security', models.SmallIntegerField(null=True, blank=True)),
                ('dockingcostpervolume', models.FloatField(null=True, db_column='dockingCostPerVolume', blank=True)),
                ('maxshipvolumedockable', models.FloatField(null=True, db_column='maxShipVolumeDockable', blank=True)),
                ('officerentalcost', models.BigIntegerField(null=True, db_column='officeRentalCost', blank=True)),
                ('operationid', models.SmallIntegerField(null=True, db_column='operationID', blank=True)),
                ('stationtypeid', models.BigIntegerField(null=True, db_column='stationTypeID', blank=True)),
                ('corporationid', models.BigIntegerField(null=True, db_column='corporationID', blank=True)),
                ('solarsystemid', models.BigIntegerField(null=True, db_column='solarSystemID', blank=True)),
                ('constellationid', models.BigIntegerField(null=True, db_column='constellationID', blank=True)),
                ('regionid', models.BigIntegerField(null=True, db_column='regionID', blank=True)),
                ('stationname', models.TextField(db_column='stationName', blank=True)),
                ('x', models.FloatField(null=True, blank=True)),
                ('y', models.FloatField(null=True, blank=True)),
                ('z', models.FloatField(null=True, blank=True)),
                ('reprocessingefficiency', models.FloatField(null=True, db_column='reprocessingEfficiency', blank=True)),
                ('reprocessingstationstake', models.FloatField(null=True, db_column='reprocessingStationsTake', blank=True)),
                ('reprocessinghangarflag', models.SmallIntegerField(null=True, db_column='reprocessingHangarFlag', blank=True)),
            ],
            options={
                'db_table': 'staStations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stastationtypes',
            fields=[
                ('stationtypeid', models.BigIntegerField(serialize=False, primary_key=True, db_column='stationTypeID')),
                ('dockentryx', models.FloatField(null=True, db_column='dockEntryX', blank=True)),
                ('dockentryy', models.FloatField(null=True, db_column='dockEntryY', blank=True)),
                ('dockentryz', models.FloatField(null=True, db_column='dockEntryZ', blank=True)),
                ('dockorientationx', models.FloatField(null=True, db_column='dockOrientationX', blank=True)),
                ('dockorientationy', models.FloatField(null=True, db_column='dockOrientationY', blank=True)),
                ('dockorientationz', models.FloatField(null=True, db_column='dockOrientationZ', blank=True)),
                ('operationid', models.SmallIntegerField(null=True, db_column='operationID', blank=True)),
                ('officeslots', models.SmallIntegerField(null=True, db_column='officeSlots', blank=True)),
                ('reprocessingefficiency', models.FloatField(null=True, db_column='reprocessingEfficiency', blank=True)),
                ('conquerable', models.NullBooleanField()),
            ],
            options={
                'db_table': 'staStationTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translationtables',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sourcetable', models.TextField(db_column='sourceTable')),
                ('destinationtable', models.TextField(db_column='destinationTable', blank=True)),
                ('translatedkey', models.TextField(db_column='translatedKey')),
                ('tcgroupid', models.BigIntegerField(null=True, db_column='tcGroupID', blank=True)),
                ('tcid', models.BigIntegerField(null=True, db_column='tcID', blank=True)),
            ],
            options={
                'db_table': 'translationTables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trntranslationcolumns',
            fields=[
                ('tcgroupid', models.SmallIntegerField(null=True, db_column='tcGroupID', blank=True)),
                ('tcid', models.SmallIntegerField(serialize=False, primary_key=True, db_column='tcID')),
                ('tablename', models.TextField(db_column='tableName')),
                ('columnname', models.TextField(db_column='columnName')),
                ('masterid', models.TextField(db_column='masterID', blank=True)),
            ],
            options={
                'db_table': 'trnTranslationColumns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trntranslationlanguages',
            fields=[
                ('numericlanguageid', models.BigIntegerField(serialize=False, primary_key=True, db_column='numericLanguageID')),
                ('languageid', models.TextField(db_column='languageID', blank=True)),
                ('languagename', models.TextField(db_column='languageName', blank=True)),
            ],
            options={
                'db_table': 'trnTranslationLanguages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trntranslations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tcid', models.SmallIntegerField(db_column='tcID')),
                ('keyid', models.BigIntegerField(db_column='keyID')),
                ('languageid', models.TextField(db_column='languageID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'trnTranslations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warcombatzones',
            fields=[
                ('combatzoneid', models.BigIntegerField(serialize=False, primary_key=True, db_column='combatZoneID')),
                ('combatzonename', models.TextField(db_column='combatZoneName', blank=True)),
                ('factionid', models.BigIntegerField(null=True, db_column='factionID', blank=True)),
                ('centersystemid', models.BigIntegerField(null=True, db_column='centerSystemID', blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'warCombatZones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warcombatzonesystems',
            fields=[
                ('solarsystemid', models.BigIntegerField(serialize=False, primary_key=True, db_column='solarSystemID')),
                ('combatzoneid', models.BigIntegerField(null=True, db_column='combatZoneID', blank=True)),
            ],
            options={
                'db_table': 'warCombatZoneSystems',
                'managed': False,
            },
        ),
    ]
